name: CI-CD Pipeline for MERN App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install backend dependencies
      run: |
        cd index  # Change to your backend directory if necessary
        npm install

    - name: Install frontend dependencies
      run: |
        cd frontend  # Ensure this is the correct name of your frontend directory
        npm install

    - name: Run backend tests
      run: |
        cd index  # Change to your backend directory to run tests
        npm test

    - name: Run frontend tests
      run: |
        cd frontend  # Ensure this is the correct name of your frontend directory
        npm test

    - name: Build frontend
      run: |
        cd frontend  # Ensure this is the correct name of your frontend directory
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./frontend/build  # Ensure this path is correct
